"""Report writer for sbom-validator — generates HTML and JSON reports.

Implements FR-15 per ADR-007: write_reports produces a matched pair of
HTML and JSON files in the specified directory.
"""

from __future__ import annotations

import importlib.metadata
import json
import logging
import string
from datetime import UTC, datetime
from pathlib import Path

from sbom_validator.models import IssueSeverity, ValidationResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Format token → report string mapping (ADR-007 §JSON Report Schema)
# ---------------------------------------------------------------------------

_FORMAT_MAP: dict[str | None, str | None] = {
    "spdx": "spdx-2.3",
    "cyclonedx": "cyclonedx-1.6",
    None: None,
}

# ---------------------------------------------------------------------------
# Issue severity sort order
# ---------------------------------------------------------------------------

_SEVERITY_ORDER: dict[str, int] = {
    IssueSeverity.ERROR: 0,
    IssueSeverity.WARNING: 1,
    IssueSeverity.INFO: 2,
}

# ---------------------------------------------------------------------------
# Status badge colours (ADR-007 §HTML Report Structure)
# ---------------------------------------------------------------------------

_STATUS_COLOUR: dict[str, str] = {
    "PASS": "#2e7d32",
    "FAIL": "#c62828",
    "ERROR": "#e65100",
}

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = string.Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SBOM Validation Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 2rem; color: #212121; }
    h1 { font-size: 1.4rem; margin-bottom: 0.5rem; }
    .meta { color: #555; font-size: 0.9rem; margin-bottom: 1.5rem; }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      border-radius: 4px;
      font-weight: bold;
      color: #fff;
      background-color: $status_colour;
    }
    .summary { margin: 1rem 0; }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(3, auto);
      gap: 1rem;
      margin-bottom: 1.5rem;
    }
    .summary-cell {
      background: #f5f5f5;
      border-radius: 4px;
      padding: 0.5rem 1rem;
      text-align: center;
    }
    .summary-cell .count { font-size: 1.5rem; font-weight: bold; }
    .summary-cell .label { font-size: 0.8rem; color: #555; }
    table {
      border-collapse: collapse;
      width: 100%;
      font-size: 0.9rem;
    }
    th {
      background: #424242;
      color: #fff;
      padding: 0.5rem 0.75rem;
      text-align: left;
    }
    td { padding: 0.45rem 0.75rem; border-bottom: 1px solid #e0e0e0; }
    tr:nth-child(even) td { background: #fafafa; }
    .sev-ERROR   { color: #c62828; font-weight: bold; }
    .sev-WARNING { color: #e65100; font-weight: bold; }
    .sev-INFO    { color: #1565c0; }
    .no-issues { color: #2e7d32; font-weight: bold; margin: 1rem 0; }
    footer { margin-top: 2rem; font-size: 0.8rem; color: #999; border-top: 1px solid #e0e0e0; padding-top: 0.5rem; }
  </style>
</head>
<body>
  <h1>SBOM Validation Report &mdash; sbom-validator v$tool_version</h1>
  <div class="meta">
    <div><strong>Generated:</strong> $generated_at</div>
    <div><strong>File:</strong> $file_path</div>
    <div><strong>Format:</strong> $format_detected</div>
    <div><strong>Status:</strong> <span class="badge">$status</span></div>
  </div>

  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="summary-cell">
      <div class="count">$error_count</div>
      <div class="label">Errors</div>
    </div>
    <div class="summary-cell">
      <div class="count">$warning_count</div>
      <div class="label">Warnings</div>
    </div>
    <div class="summary-cell">
      <div class="count">$info_count</div>
      <div class="label">Info</div>
    </div>
  </div>

  <h2>Issues</h2>
  $issues_section

  <footer>Generated by sbom-validator v$tool_version</footer>
</body>
</html>
""")

# ---------------------------------------------------------------------------
# Helper: escape HTML special characters for safe insertion into templates
# ---------------------------------------------------------------------------

_HTML_ESCAPES: dict[str, str] = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
}


def _escape(text: str) -> str:
    """Escape HTML special characters in *text*."""
    for char, replacement in _HTML_ESCAPES.items():
        text = text.replace(char, replacement)
    return text


# ---------------------------------------------------------------------------
# Helper: resolve tool version
# ---------------------------------------------------------------------------


def _tool_version() -> str:
    """Return the installed package version, falling back to 'unknown'."""
    try:
        return importlib.metadata.version("sbom-validator")
    except importlib.metadata.PackageNotFoundError:
        return "unknown"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_reports(
    result: ValidationResult,
    report_dir: Path,
) -> tuple[Path, Path]:
    """Write HTML and JSON reports for a completed validation run.

    Creates report_dir if it does not already exist.

    Args:
        result: The completed ValidationResult from the validator pipeline.
        report_dir: Directory in which to write the two report files.

    Returns:
        A two-tuple (html_path, json_path) of the paths actually written.

    Raises:
        OSError: If the directory cannot be created or the files cannot
                 be written (e.g., permission denied).
    """
    # Compute shared timestamp and stems once.
    now_utc = datetime.now(UTC)
    timestamp = now_utc.strftime("%Y%m%d-%H%M%S")
    generated_at = now_utc.strftime("%Y-%m-%dT%H:%M:%SZ")
    stem = Path(result.file_path).stem
    version = _tool_version()

    # Ensure destination directory exists.
    report_dir.mkdir(parents=True, exist_ok=True)

    # Derive filenames.
    html_path = report_dir / f"sbom-report-{stem}-{timestamp}.html"
    json_path = report_dir / f"sbom-report-{stem}-{timestamp}.json"

    # Expand format token.
    format_detected_expanded = _FORMAT_MAP.get(result.format_detected, None)

    # Sort issues: ERROR → WARNING → INFO, preserving original order within groups.
    sorted_issues = sorted(
        result.issues,
        key=lambda i: _SEVERITY_ORDER.get(str(i.severity), 99),
    )

    # Compute severity counts.
    error_count = sum(1 for i in result.issues if i.severity == IssueSeverity.ERROR)
    warning_count = sum(1 for i in result.issues if i.severity == IssueSeverity.WARNING)
    info_count = sum(1 for i in result.issues if i.severity == IssueSeverity.INFO)

    # -----------------------------------------------------------------------
    # Build HTML report
    # -----------------------------------------------------------------------
    status_colour = _STATUS_COLOUR.get(str(result.status), "#424242")
    format_display = format_detected_expanded if format_detected_expanded is not None else "Unknown"

    if sorted_issues:
        rows = "\n".join(
            f"    <tr>"
            f'<td class="sev-{_escape(str(issue.severity))}">{_escape(str(issue.severity))}</td>'
            f"<td>{_escape(issue.rule)}</td>"
            f"<td>{_escape(issue.field_path)}</td>"
            f"<td>{_escape(issue.message)}</td>"
            f"</tr>"
            for issue in sorted_issues
        )
        issues_section = (
            "<table>\n"
            "  <thead>\n"
            "    <tr><th>Severity</th><th>Rule</th><th>Field Path</th><th>Message</th></tr>\n"
            "  </thead>\n"
            "  <tbody>\n"
            f"{rows}\n"
            "  </tbody>\n"
            "</table>"
        )
    else:
        issues_section = '<p class="no-issues">No issues found.</p>'

    html_content = _HTML_TEMPLATE.substitute(
        tool_version=_escape(version),
        generated_at=_escape(generated_at),
        file_path=_escape(result.file_path),
        format_detected=_escape(format_display),
        status=_escape(str(result.status)),
        status_colour=status_colour,
        error_count=error_count,
        warning_count=warning_count,
        info_count=info_count,
        issues_section=issues_section,
    )
    html_path.write_text(html_content, encoding="utf-8")

    # -----------------------------------------------------------------------
    # Build JSON report
    # -----------------------------------------------------------------------
    json_data: dict[object, object] = {
        "generated_at": generated_at,
        "tool_version": version,
        "file_path": result.file_path,
        "format_detected": format_detected_expanded,
        "status": str(result.status),
        "summary": {
            "error_count": error_count,
            "warning_count": warning_count,
            "info_count": info_count,
        },
        "issues": [
            {
                "severity": str(issue.severity),
                "rule": issue.rule,
                "field_path": issue.field_path,
                "message": issue.message,
            }
            for issue in sorted_issues
        ],
    }
    json_path.write_text(json.dumps(json_data, indent=2), encoding="utf-8")

    logger.info("Reports written: HTML=%s  JSON=%s", html_path, json_path)

    return html_path, json_path
